name: Build
on:
  push:
     branches:
     - main
jobs:
   my_job:
      runs-on: windows-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v2
